[package]
name = "todo-man"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.5"
termsize = "0.1"
ctrlc = { version = "3.2.5", features = ["termination"] }